# Generated by Django 5.2.1 on 2025-08-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('division', models.CharField(default='Chattogram', max_length=100)),
                ('address', models.CharField(default='Unknown', max_length=255)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('blood_group', models.CharField(default='A+', max_length=5)),
                ('rh_factor', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', max_length=2)),
                ('hb_level', models.FloatField(default=0.0)),
                ('medical_issue', models.CharField(blank=True, default='', max_length=255)),
                ('mobile', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=25)),
                ('surname', models.CharField(default='User', max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(default='Unknown', max_length=255)),
                ('blood_group', models.CharField(max_length=5)),
                ('blood_component', models.CharField(default='Packed Cell', max_length=100)),
                ('number_of_bags', models.PositiveIntegerField(default=1)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.donor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people')),
            ],
        ),
    ]
